### PR TITLE
Add tag_push_events hook

### PR DESCRIPTION
**Pull request by depay**

### CODE REVIEW

**Comment by depay** [comment]
we are now working with drone ci, and we wanna trigger some operation by tag event on gitlab.

**Comment by Bugagazavr** [comment]
sorry for delay, currently `0.3` branch uses this, if we update this repo drone `0.3` it will be broken, can you implement this feature in `0.3` before.

**Comment by depay** [comment]
@Bugagazavr  PR submitted https://github.com/drone/drone/pull/1130

**Comment by Bugagazavr** [comment]
thanks

2015-08-10 5:30 GMT+03:00 depay <notifications@github.com>:

**Pull request merged**
